# Generated by Django 4.2.22 on 2025-06-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('message', models.TextField()),
                ('remind_by', models.CharField(choices=[('SMS', 'sms'), ('EMAIL', 'email')], max_length=10)),
            ],
        ),
    ]
